const skill = [
  "---",
  "name: shadowclone",
  "description: Delegate a bounded task to the shadowclone subagent, a copy of the user that follows their learned engineering profile",
  "---",
  "",
  "# Delegate to the shadowclone subagent",
  "",
  "## Use when",
  "",
  "The user asks for a clone by name, or asks shadowclone to take a task.",
  "",
  "Also use it when the work in front of you contains a bounded piece that can run in parallel without blocking the thread you are on, and you can state its scope in one paragraph.",
  "",
  "Do not delegate work that depends on a decision the user has not made yet.",
  "",
  "## Process",
  "",
  'Spawn the clone with the `Agent` tool and `subagent_type: "shadowclone"`. Write the prompt as a delegation brief. The clone does not see this conversation, so the brief carries everything it needs:',
  "",
  "- **Objective.** What finished work looks like, in one sentence.",
  "- **Context.** The files, functions, and findings it needs, with paths.",
  "- **Constraints.** What must not change, and any convention its profile does not already carry.",
  "- **Validation.** The exact command that proves the work, and what passing looks like.",
  "- **Expected result.** What it should report back.",
  "",
  "## Guardrails",
  "",
  "Never forward the user's message verbatim. A clone handed a raw request without context repeats work you have already done.",
  "",
  "Give one task to one clone. Two clones editing the same file produce a conflict the user has to resolve.",
  "",
  "The clone does not inherit your approvals. Anything that sends, commits, pushes, or spends stays with you.",
  "",
  "## Completion",
  "",
  "Report which task went to the clone, what it returned, and what you verified yourself.",
  "",
].join("\n");

export function renderDelegationSkill(): string {
  return skill;
}
