import { type BuiltInRule, javascriptFiles, javascriptTestFiles } from "./types";

const secretWords = "(?:token|secret|password|passwd|nonce|salt|session|otp|api_?key)";

export const javascriptRules: readonly BuiltInRule[] = [
  {
    id: "js-focused-test",
    level: "certain",
    severity: "high",
    category: "correctness",
    files: javascriptTestFiles,
    pattern: /\b(?:describe|it|test|context|suite)\.only\s*\(/,
    title: "Focused test skips the rest of the suite",
    failure: "The runner executes only this test, so every other test in the file or suite stops running in CI.",
    examples: { hit: 'it.only("parses", () => {', miss: 'it("parses", () => {' },
  },
  {
    id: "js-eval",
    level: "signal",
    severity: "high",
    category: "security",
    files: javascriptFiles,
    pattern: /(?<![\w.$])eval\s*\(|\bnew\s+Function\s*\(/,
    title: "Code built from a string at runtime",
    failure: "If any part of the string comes from input, the input runs as code.",
    examples: { hit: "const result = eval(expression);", miss: "const result = retrieval(expression);" },
  },
  {
    id: "js-html-injection",
    level: "signal",
    severity: "medium",
    category: "security",
    files: javascriptFiles,
    pattern: /\.(?:innerHTML|outerHTML)\s*\+?=(?!=)|dangerouslySetInnerHTML\s*=\s*\{|\bdocument\.write(?:ln)?\s*\(|\.insertAdjacentHTML\s*\(/,
    title: "HTML written from a string",
    failure: "Text that reaches this sink unescaped runs as script in the user's browser.",
    examples: { hit: "element.innerHTML = message;", miss: "element.textContent = message;" },
  },
  {
    id: "js-shell-command",
    level: "signal",
    severity: "high",
    category: "security",
    files: javascriptFiles,
    pattern: /\b(?:exec|execSync)\s*\(\s*`[^`]*\$\{|\bshell\s*:\s*true\b/,
    title: "Shell command built with interpolation",
    failure: "A value with shell syntax such as `; rm -rf` runs as a second command.",
    examples: { hit: `execSync(\`git checkout \${branch}\`);`, miss: 'execFileSync("git", ["checkout", branch]);' },
  },
  {
    id: "js-tls-verification-off",
    level: "signal",
    severity: "high",
    category: "security",
    files: javascriptFiles,
    pattern: /\brejectUnauthorized\s*:\s*false\b/,
    title: "TLS certificate checks turned off",
    failure: "The client accepts any certificate, so a network attacker can read and change the traffic.",
    examples: { hit: "const agent = new Agent({ rejectUnauthorized: false });", miss: "const agent = new Agent({ rejectUnauthorized: true });" },
  },
  {
    id: "js-weak-hash",
    level: "signal",
    severity: "medium",
    category: "security",
    files: javascriptFiles,
    pattern: /\bcreateHash\s*\(\s*['"`](?:md5|sha1)['"`]/i,
    title: "Weak hash algorithm",
    failure: "MD5 and SHA-1 collisions are practical, so the hash cannot protect integrity or passwords.",
    examples: { hit: 'createHash("md5").update(value)', miss: 'createHash("sha256").update(value)' },
  },
  {
    id: "js-insecure-random",
    level: "signal",
    severity: "low",
    category: "security",
    files: javascriptFiles,
    pattern: new RegExp(`${secretWords}.*Math\\.random\\s*\\(|Math\\.random\\s*\\(.*${secretWords}`, "i"),
    title: "Predictable random value used for a secret",
    failure: "Math.random output can be predicted, so an attacker can guess the token.",
    examples: { hit: "const token = Math.random().toString(36);", miss: "const jitter = Math.random() * 100;" },
  },
  {
    id: "js-sql-interpolation",
    level: "signal",
    severity: "high",
    category: "security",
    files: javascriptFiles,
    pattern: /\b(?:query|execute|raw|unsafe)\s*\(\s*`[^`]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^`]*\$\{|\$(?:queryRawUnsafe|executeRawUnsafe)\s*\(/i,
    title: "SQL built with string interpolation",
    failure: "A value with a quote changes the query, which allows SQL injection.",
    examples: { hit: `db.query(\`SELECT * FROM users WHERE id = \${id}\`);`, miss: 'db.query("SELECT * FROM users WHERE id = $1", [id]);' },
  },
  {
    id: "js-jwt-none",
    level: "signal",
    severity: "high",
    category: "security",
    files: javascriptFiles,
    pattern: /algorithms?\s*:\s*\[?\s*['"`]none['"`]/i,
    title: "JWT accepts the none algorithm",
    failure: "A token with no signature passes verification, so anyone can forge one.",
    examples: { hit: 'jwt.verify(token, key, { algorithms: ["none"] });', miss: 'jwt.verify(token, key, { algorithms: ["HS256"] });' },
  },
  {
    id: "js-postmessage-any-origin",
    level: "signal",
    severity: "medium",
    category: "security",
    files: javascriptFiles,
    pattern: /\.postMessage\s*\([^)]*,\s*['"`]\*['"`]\s*\)/,
    title: "postMessage to any origin",
    failure: "Any page that holds a reference to this window receives the message data.",
    examples: { hit: 'parent.postMessage(payload, "*");', miss: "parent.postMessage(payload, origin);" },
  },
  {
    id: "js-prototype-key",
    level: "signal",
    severity: "medium",
    category: "security",
    files: javascriptFiles,
    pattern: /\[\s*['"`]__proto__['"`]\s*\]|\.__proto__\s*=(?!=)/,
    title: "Write through __proto__",
    failure: "Writing through the prototype changes every object of that type, which can bypass checks.",
    examples: { hit: 'target["__proto__"] = value;', miss: "Object.setPrototypeOf(target, null);" },
  },
  {
    id: "js-request-to-sink",
    level: "signal",
    severity: "medium",
    category: "security",
    files: javascriptFiles,
    pattern: /\b(?:redirect|readFile|readFileSync|createReadStream|sendFile|fetch|axios(?:\.\w+)?|got)\s*\(\s*(?:[^)]*,\s*)?req\.(?:query|body|params)/,
    title: "Request input used as a URL or path",
    failure: "A crafted value redirects users, reads files outside the intended folder, or makes the server call internal hosts.",
    examples: { hit: "res.redirect(req.query.next);", miss: 'res.redirect("/home");' },
  },
  {
    id: "js-string-timer",
    level: "signal",
    severity: "medium",
    category: "security",
    files: javascriptFiles,
    pattern: /\bset(?:Timeout|Interval)\s*\(\s*['"`]/,
    title: "Timer runs a string as code",
    failure: "The string is evaluated like eval, so input inside it runs as code.",
    examples: { hit: 'setTimeout("refresh()", 100);', miss: "setTimeout(refresh, 100);" },
  },
  {
    id: "js-debugger",
    level: "signal",
    severity: "low",
    category: "correctness",
    files: javascriptFiles,
    pattern: /^\s*debugger\s*;?\s*$/,
    title: "Debugger statement left in",
    failure: "Execution pauses here whenever developer tools are open.",
    examples: { hit: "  debugger;", miss: "  const debuggerEnabled = true;" },
  },
];
