import { type BuiltInRule, goFiles, rustFiles } from "./types";

const secretWords = "(?:token|secret|password|passwd|nonce|salt|session|otp|key)";

export const systemsRules: readonly BuiltInRule[] = [
  {
    id: "go-tls-verification-off",
    level: "signal",
    severity: "high",
    category: "security",
    files: goFiles,
    pattern: /\bInsecureSkipVerify\s*:\s*true\b/,
    title: "TLS certificate checks turned off",
    failure: "The client accepts any certificate, so a network attacker can read and change the traffic.",
    examples: { hit: "TLSClientConfig: &tls.Config{InsecureSkipVerify: true},", miss: "TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12}," },
  },
  {
    id: "go-shell-command",
    level: "signal",
    severity: "high",
    category: "security",
    files: goFiles,
    pattern: /\bexec\.Command(?:Context)?\s*\([^)]*"(?:\/bin\/)?(?:ba)?sh"\s*,\s*"-c"/,
    title: "Command runs through a shell",
    failure: "A value with shell syntax runs as a second command.",
    examples: { hit: 'cmd := exec.Command("sh", "-c", script)', miss: 'cmd := exec.Command("git", "status")' },
  },
  {
    id: "go-weak-hash",
    level: "signal",
    severity: "medium",
    category: "security",
    files: goFiles,
    pattern: /\b(?:md5|sha1)\.(?:New|Sum)\s*\(/,
    title: "Weak hash algorithm",
    failure: "MD5 and SHA-1 collisions are practical, so the hash cannot protect integrity or passwords.",
    examples: { hit: "sum := md5.Sum(data)", miss: "sum := sha256.Sum256(data)" },
  },
  {
    id: "go-insecure-random",
    level: "signal",
    severity: "low",
    category: "security",
    files: goFiles,
    pattern: new RegExp(`\\brand\\.(?:Int|Intn|Int63|Uint64|Read)\\b.*${secretWords}|${secretWords}.*\\brand\\.(?:Int|Intn|Int63|Uint64)\\b`, "i"),
    title: "Predictable random value used for a secret",
    failure: "math/rand is predictable, so an attacker can guess the value. Use crypto/rand.",
    examples: { hit: "token := fmt.Sprint(rand.Int63())", miss: "delay := time.Duration(rand.Intn(100))" },
  },
  {
    id: "go-sql-formatting",
    level: "signal",
    severity: "high",
    category: "security",
    files: goFiles,
    pattern: /\bfmt\.Sprintf\s*\(\s*"[^"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b/i,
    title: "SQL built with string formatting",
    failure: "A value with a quote changes the query, which allows SQL injection.",
    examples: { hit: 'query := fmt.Sprintf("SELECT * FROM users WHERE id = %s", id)', miss: 'row := db.QueryRow("SELECT * FROM users WHERE id = $1", id)' },
  },
  {
    id: "go-unsafe",
    level: "signal",
    severity: "medium",
    category: "security",
    files: goFiles,
    pattern: /\bunsafe\.Pointer\b|\btemplate\.HTML\s*\(/,
    title: "Type safety or HTML escaping bypassed",
    failure: "unsafe.Pointer can corrupt memory, and template.HTML renders input without escaping.",
    examples: { hit: "out := template.HTML(comment)", miss: "out := template.HTMLEscapeString(comment)" },
  },
  {
    id: "rust-unsafe",
    level: "signal",
    severity: "medium",
    category: "security",
    files: rustFiles,
    pattern: /\bunsafe\s*\{|\bunsafe\s+(?:fn|impl)\b|\bmem::transmute\b/,
    title: "Unsafe Rust",
    failure: "The compiler no longer checks memory safety here, so a wrong assumption corrupts memory.",
    examples: { hit: "let value = unsafe { *pointer };", miss: "let value = *reference;" },
  },
  {
    id: "rust-tls-verification-off",
    level: "signal",
    severity: "high",
    category: "security",
    files: rustFiles,
    pattern: /\bdanger_accept_invalid_(?:certs|hostnames)\s*\(\s*true\s*\)/,
    title: "TLS certificate checks turned off",
    failure: "The client accepts any certificate, so a network attacker can read and change the traffic.",
    examples: { hit: ".danger_accept_invalid_certs(true)", miss: ".danger_accept_invalid_certs(false)" },
  },
  {
    id: "rust-shell-command",
    level: "signal",
    severity: "high",
    category: "security",
    files: rustFiles,
    pattern: /\bCommand::new\s*\(\s*"(?:\/bin\/)?(?:ba)?sh"\s*\)/,
    title: "Command runs through a shell",
    failure: "A value with shell syntax runs as a second command.",
    examples: { hit: 'Command::new("sh").arg("-c").arg(script)', miss: 'Command::new("git").arg("status")' },
  },
  {
    id: "rust-sql-formatting",
    level: "signal",
    severity: "high",
    category: "security",
    files: rustFiles,
    pattern: /\bformat!\s*\(\s*"[^"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b/i,
    title: "SQL built with string formatting",
    failure: "A value with a quote changes the query, which allows SQL injection.",
    examples: { hit: 'let query = format!("SELECT * FROM users WHERE id = {}", id);', miss: 'sqlx::query("SELECT * FROM users WHERE id = $1").bind(id)' },
  },
  {
    id: "rust-unfinished",
    level: "signal",
    severity: "medium",
    category: "correctness",
    files: rustFiles,
    pattern: /\b(?:todo|unimplemented)!\s*\(/,
    title: "Unfinished code panics at runtime",
    failure: "Reaching this line panics and stops the thread.",
    examples: { hit: "    todo!()", miss: "    // a todo list" },
  },
];
