import { type BuiltInRule, workflowFiles } from "./types";

export const workflowRules: readonly BuiltInRule[] = [
  {
    id: "actions-expression-injection",
    level: "signal",
    severity: "high",
    category: "security",
    files: workflowFiles,
    pattern: /\$\{\{\s*github\.(?:event\.(?:issue|pull_request|comment|review|review_comment|discussion|head_commit|commits|pages)[\w.[\]*]*\.(?:title|body|message|name|ref|label|email)|head_ref)\s*\}\}/,
    title: "Untrusted event text expanded into the workflow",
    failure: "Inside a run step, a title or branch name with shell syntax runs as a command with the workflow's token.",
    examples: { hit: `run: echo "\${{ github.event.pull_request.title }}"`, miss: 'run: echo "$PULL_REQUEST_TITLE"' },
  },
  {
    id: "actions-pull-request-target",
    level: "signal",
    severity: "high",
    category: "security",
    files: workflowFiles,
    pattern: /^\s*pull_request_target\s*:?/,
    title: "Workflow runs with secrets on pull requests from forks",
    failure: "If the job checks out or runs the pull request's code, a fork can read the repository's secrets.",
    examples: { hit: "  pull_request_target:", miss: "  pull_request:" },
  },
  {
    id: "actions-checkout-pull-request-head",
    level: "signal",
    severity: "high",
    category: "security",
    files: workflowFiles,
    pattern: /\bref\s*:\s*\$\{\{\s*github\.event\.pull_request\.head\.(?:sha|ref)\s*\}\}/,
    title: "Workflow checks out the pull request head",
    failure: "In a privileged workflow, the pull request's code runs with the workflow's secrets and token.",
    examples: { hit: `ref: \${{ github.event.pull_request.head.sha }}`, miss: `ref: \${{ github.sha }}` },
  },
  {
    id: "actions-write-all",
    level: "signal",
    severity: "medium",
    category: "security",
    files: workflowFiles,
    pattern: /^\s*permissions\s*:\s*write-all\b/,
    title: "Workflow token can write everything",
    failure: "Any step or action in the job can push code, change releases, and edit settings.",
    examples: { hit: "permissions: write-all", miss: "permissions: read-all" },
  },
  {
    id: "actions-unpinned-third-party",
    level: "signal",
    severity: "low",
    category: "security",
    files: workflowFiles,
    pattern: /^\s*-?\s*uses\s*:\s*(?!actions\/|github\/|\.\/|docker:\/\/)[\w.-]+\/[\w./-]+@(?![a-f0-9]{40}\b)/,
    title: "Third-party action pinned to a movable tag",
    failure: "The action's owner can move the tag, and the next run executes the new code with the job's token.",
    examples: { hit: "      - uses: someone/setup-tool@v2", miss: "      - uses: actions/checkout@v4" },
  },
];
