export const packageNames = [
  "core",
  "redact",
  "agents",
  "sessions",
  "review",
  "changes",
  "skills",
  "profile",
  "environment",
  "builds",
  "learning",
  "harness",
  "cloud",
  "web",
  "mcp",
  "cli",
] as const;

export type PackageName = (typeof packageNames)[number];

export type PackageLayout = {
  readonly sourceRoot: string;
  readonly modules: Readonly<Record<PackageName, readonly string[]>>;
  readonly allowedDependencies: Readonly<Record<PackageName, readonly PackageName[]>>;
};

export const packageLayout: PackageLayout = {
  sourceRoot: "src",
  modules: {
    core: ["paths", "distribution", "testing", "product", "io", "storage", "localFiles", "config"],
    redact: ["redact"],
    agents: ["engine", "provider"],
    sessions: ["observe", "eventIndex", "signal"],
    review: ["review"],
    changes: ["changes"],
    skills: ["skills", "skillMaintenance"],
    profile: ["profile", "references", "migrate"],
    environment: ["environment", "integrations"],
    builds: ["builds"],
    learning: ["learning", "distill", "preferences", "importRules"],
    harness: ["harness"],
    cloud: ["cloud"],
    web: ["web"],
    mcp: ["mcp"],
    cli: ["cli"],
  },
  allowedDependencies: {
    core: [],
    redact: ["core"],
    agents: ["core", "redact"],
    sessions: ["core", "redact"],
    review: ["core", "redact", "agents"],
    changes: ["core", "sessions"],
    skills: ["core", "sessions", "changes"],
    profile: ["core", "redact", "sessions", "changes", "skills"],
    environment: ["core", "redact", "agents", "sessions", "changes", "skills", "profile"],
    builds: ["core", "redact", "changes", "skills", "environment"],
    learning: [
      "core",
      "redact",
      "agents",
      "sessions",
      "changes",
      "skills",
      "profile",
      "environment",
    ],
    harness: ["core", "redact", "sessions", "changes", "skills", "profile", "environment"],
    cloud: ["core", "sessions", "review", "environment"],
    web: [
      "core",
      "redact",
      "agents",
      "sessions",
      "skills",
      "environment",
      "builds",
      "learning",
      "cloud",
    ],
    mcp: [
      "core",
      "sessions",
      "changes",
      "skills",
      "profile",
      "environment",
      "learning",
      "cloud",
      "web",
    ],
    cli: [
      "core",
      "redact",
      "agents",
      "sessions",
      "review",
      "changes",
      "skills",
      "profile",
      "environment",
      "builds",
      "learning",
      "harness",
      "cloud",
      "web",
      "mcp",
    ],
  },
};
