import { expect, test } from "bun:test";
import path from "node:path";
import { treeWith } from "./boundaries/testing";
import { checkPackageGuides } from "./packageGuides";
import { renderFacts } from "./packageGuides/facts";
import { readWorkspaces } from "./packageGuides/workspaces";

const alphaManifest = JSON.stringify({
  name: "@scope/alpha",
  dependencies: { "@scope/beta": "workspace:*", zod: "^4.0.0" },
  exports: { ".": "./src/index.ts", "./testing": "./src/testing.ts" },
});
const betaManifest = JSON.stringify({ name: "@scope/beta" });
const rootManifest = JSON.stringify({ workspaces: ["packages/*", "tooling"] });
const alphaFacts = [
  "<!-- package-facts:start -->",
  "",
  "(generated by `bun run guides`; do not edit by hand)",
  "",
  "- Package name: `@scope/alpha`",
  "- Workspace dependencies: `@scope/beta`",
  "- External dependencies: `zod`",
  "- Export subpaths: `.`, `./testing`",
  "",
  "<!-- package-facts:end -->",
].join("\n");
const betaFacts = [
  "<!-- package-facts:start -->",
  "",
  "(generated by `bun run guides`; do not edit by hand)",
  "",
  "- Package name: `@scope/beta`",
  "- Workspace dependencies: none",
  "- External dependencies: none",
  "- Export subpaths: none",
  "",
  "<!-- package-facts:end -->",
].join("\n");

const toolingFacts = [
  "<!-- package-facts:start -->",
  "",
  "(generated by `bun run guides`; do not edit by hand)",
  "",
  "- Package name: `@scope/tooling`",
  "- Workspace dependencies: none",
  "- External dependencies: none",
  "- Export subpaths: none",
  "",
  "<!-- package-facts:end -->",
].join("\n");

function guide(facts: string): string {
  return `# Guide\n\nBefore the block.\n\n${facts}\n\n## Rules\n\nAfter the block.\n`;
}

function currentTree(): Record<string, string> {
  return {
    "package.json": rootManifest,
    "packages/alpha/package.json": alphaManifest,
    "packages/alpha/AGENTS.md": guide(alphaFacts),
    "packages/alpha/CLAUDE.md": "@AGENTS.md\n",
    "packages/beta/package.json": betaManifest,
    "packages/beta/AGENTS.md": guide(betaFacts),
    "packages/beta/CLAUDE.md": "@AGENTS.md\n",
    "tooling/package.json": JSON.stringify({ name: "@scope/tooling" }),
    "tooling/AGENTS.md": guide(toolingFacts),
    "tooling/CLAUDE.md": "@AGENTS.md\n",
  };
}

function currentTreeWithout(file: string): Record<string, string> {
  return Object.fromEntries(Object.entries(currentTree()).filter(([name]) => name !== file));
}

test("the facts block lists the name, both kinds of dependency, and the export subpaths", async () => {
  const rootDirectory = await treeWith(currentTree());
  const [alpha] = await readWorkspaces({ rootDirectory });

  expect(alpha && renderFacts(alpha)).toBe(alphaFacts);
});

test("a tree with current guides passes and every workspace in the root manifest is checked", async () => {
  const rootDirectory = await treeWith(currentTree());

  expect(await checkPackageGuides({ rootDirectory, write: false })).toEqual({
    workspaceCount: 3,
    updatedFiles: [],
    problems: [],
  });
});

test("a workspace with no AGENTS.md fails", async () => {
  const rootDirectory = await treeWith(currentTreeWithout("packages/beta/AGENTS.md"));

  const report = await checkPackageGuides({ rootDirectory, write: false });

  expect(report.problems).toEqual([{ file: "packages/beta/AGENTS.md", message: "is missing" }]);
});

test("a CLAUDE.md that is not exactly the import fails, and so does a missing one", async () => {
  const rootDirectory = await treeWith({
    ...currentTreeWithout("packages/beta/CLAUDE.md"),
    "packages/alpha/CLAUDE.md": "@AGENTS.md\nExtra text\n",
  });

  const report = await checkPackageGuides({ rootDirectory, write: false });

  expect(report.problems.map((problem) => problem.file)).toEqual([
    "packages/alpha/CLAUDE.md",
    "packages/beta/CLAUDE.md",
  ]);
});

test("a facts block that no longer matches package.json fails", async () => {
  const rootDirectory = await treeWith({
    ...currentTree(),
    "packages/alpha/package.json": JSON.stringify({
      name: "@scope/alpha",
      dependencies: { "@scope/beta": "workspace:*", zod: "^4.0.0", commander: "^15.0.0" },
      exports: { ".": "./src/index.ts", "./testing": "./src/testing.ts" },
    }),
  });

  const report = await checkPackageGuides({ rootDirectory, write: false });

  expect(report.problems).toEqual([
    {
      file: "packages/alpha/AGENTS.md",
      message: "has a package-facts block that is out of date",
    },
  ]);
});

test("a guide with no facts markers fails", async () => {
  const rootDirectory = await treeWith({
    ...currentTree(),
    "packages/beta/AGENTS.md": "# Guide\n\nNo block.\n",
  });

  const report = await checkPackageGuides({ rootDirectory, write: false });

  expect(report.problems).toEqual([
    { file: "packages/beta/AGENTS.md", message: "needs one package-facts block" },
  ]);
});

test("write mode fixes only the facts block and leaves the rest of the guide alone", async () => {
  const stale = guide(alphaFacts.replace("`zod`", "`zod`, `old-package`"));
  const rootDirectory = await treeWith({ ...currentTree(), "packages/alpha/AGENTS.md": stale });

  const report = await checkPackageGuides({ rootDirectory, write: true });

  expect(report).toEqual({
    workspaceCount: 3,
    updatedFiles: ["packages/alpha/AGENTS.md"],
    problems: [],
  });
  expect(await Bun.file(path.join(rootDirectory, "packages/alpha/AGENTS.md")).text()).toBe(
    guide(alphaFacts),
  );
  expect((await checkPackageGuides({ rootDirectory, write: false })).problems).toEqual([]);
});

test("write mode still reports a missing guide and a wrong CLAUDE.md, and creates neither", async () => {
  const rootDirectory = await treeWith({
    ...currentTreeWithout("packages/beta/AGENTS.md"),
    "packages/alpha/CLAUDE.md": "wrong\n",
  });

  const report = await checkPackageGuides({ rootDirectory, write: true });

  expect(report.problems.map((problem) => problem.file)).toEqual([
    "packages/alpha/CLAUDE.md",
    "packages/beta/AGENTS.md",
  ]);
  expect(await Bun.file(path.join(rootDirectory, "packages/beta/AGENTS.md")).exists()).toBe(false);
});
