import { type BuiltInRule, csharpFiles, jvmFiles } from "./types";

const secretWords = "(?:token|secret|password|passwd|nonce|salt|session|otp|apiKey)";

export const managedRules: readonly BuiltInRule[] = [
  {
    id: "jvm-shell-command",
    level: "signal",
    severity: "high",
    category: "security",
    files: jvmFiles,
    pattern: /\bRuntime\.getRuntime\(\)\.exec\s*\(|\bProcessBuilder\s*\([^)]*"(?:\/bin\/)?(?:ba)?sh"\s*,\s*"-c"/,
    title: "Command built and run at runtime",
    failure: "A value with shell syntax or extra arguments runs commands that the code did not intend.",
    examples: { hit: "Runtime.getRuntime().exec(command);", miss: 'new ProcessBuilder("git", "status").start();' },
  },
  {
    id: "jvm-unsafe-deserialization",
    level: "signal",
    severity: "high",
    category: "security",
    files: jvmFiles,
    pattern: /\bnew\s+ObjectInputStream\s*\(|\bXMLDecoder\s*\(|\benableDefaultTyping\s*\(/,
    title: "Unsafe deserialization",
    failure: "Deserializing attacker-controlled bytes can run code through gadget classes on the classpath.",
    examples: { hit: "ObjectInputStream input = new ObjectInputStream(stream);", miss: "DataInputStream input = new DataInputStream(stream);" },
  },
  {
    id: "jvm-weak-hash",
    level: "signal",
    severity: "medium",
    category: "security",
    files: jvmFiles,
    pattern: /MessageDigest\.getInstance\s*\(\s*"(?:MD5|SHA-?1)"/i,
    title: "Weak hash algorithm",
    failure: "MD5 and SHA-1 collisions are practical, so the hash cannot protect integrity or passwords.",
    examples: { hit: 'MessageDigest.getInstance("MD5")', miss: 'MessageDigest.getInstance("SHA-256")' },
  },
  {
    id: "jvm-insecure-random",
    level: "signal",
    severity: "low",
    category: "security",
    files: jvmFiles,
    pattern: new RegExp(`${secretWords}.*\\bnew\\s+Random\\s*\\(|\\bnew\\s+Random\\s*\\(.*${secretWords}`, "i"),
    title: "Predictable random value used for a secret",
    failure: "java.util.Random is predictable, so an attacker can guess the value. Use SecureRandom.",
    examples: { hit: "String token = Long.toString(new Random().nextLong());", miss: "int delay = new Random().nextInt(100);" },
  },
  {
    id: "jvm-sql-concatenation",
    level: "signal",
    severity: "high",
    category: "security",
    files: jvmFiles,
    pattern: /\b(?:createQuery|createNativeQuery|executeQuery|executeUpdate|execute|prepareStatement)\s*\(\s*"[^"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^"]*"\s*\+/i,
    title: "SQL built with string concatenation",
    failure: "A value with a quote changes the query, which allows SQL injection.",
    examples: { hit: 'statement.executeQuery("SELECT * FROM users WHERE id = " + id);', miss: 'connection.prepareStatement("SELECT * FROM users WHERE id = ?");' },
  },
  {
    id: "jvm-tls-verification-off",
    level: "signal",
    severity: "high",
    category: "security",
    files: jvmFiles,
    pattern: /\bTrustAll\w*|\bALLOW_ALL_HOSTNAME_VERIFIER\b|\bNoopHostnameVerifier\b|setHostnameVerifier\s*\(\s*\([^)]*\)\s*->\s*true/,
    title: "TLS certificate or hostname checks turned off",
    failure: "The client accepts any certificate or host, so a network attacker can read and change the traffic.",
    examples: { hit: "builder.setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE);", miss: "builder.setSSLHostnameVerifier(new DefaultHostnameVerifier());" },
  },
  {
    id: "jvm-csrf-disabled",
    level: "signal",
    severity: "medium",
    category: "security",
    files: jvmFiles,
    pattern: /\.csrf\s*\(\s*\)\s*\.disable\s*\(|csrf\s*\(\s*\w+\s*->\s*\w+\.disable\s*\(\s*\)\s*\)|csrf\s*\(\s*AbstractHttpConfigurer::disable\s*\)/,
    title: "CSRF protection turned off",
    failure: "Another site can submit state-changing requests with the user's session cookie.",
    examples: { hit: "http.csrf(csrf -> csrf.disable());", miss: "http.csrf(Customizer.withDefaults());" },
  },
  {
    id: "jvm-xml-parser",
    level: "signal",
    severity: "medium",
    category: "security",
    files: jvmFiles,
    pattern: /\b(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory)\.newInstance\s*\(/,
    title: "XML parser without visible external entity limits",
    failure: "If external entities stay enabled, a crafted document reads local files or calls internal hosts.",
    examples: { hit: "DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();", miss: "Document document = builder.parse(source);" },
  },
  {
    id: "csharp-unsafe-deserialization",
    level: "signal",
    severity: "high",
    category: "security",
    files: csharpFiles,
    pattern: /\b(?:BinaryFormatter|NetDataContractSerializer|SoapFormatter|LosFormatter)\b|TypeNameHandling\s*=\s*TypeNameHandling\.(?:All|Auto|Objects|Arrays)/,
    title: "Unsafe deserialization",
    failure: "Deserializing attacker-controlled data with type names can run arbitrary code.",
    examples: { hit: "var formatter = new BinaryFormatter();", miss: "var options = new JsonSerializerOptions();" },
  },
  {
    id: "csharp-shell-command",
    level: "signal",
    severity: "high",
    category: "security",
    files: csharpFiles,
    pattern: /\bProcess\.Start\s*\(\s*"(?:cmd(?:\.exe)?|powershell(?:\.exe)?|pwsh|\/bin\/(?:ba)?sh)"/i,
    title: "Command runs through a shell",
    failure: "A value with shell syntax runs as a second command.",
    examples: { hit: 'Process.Start("cmd.exe", "/c " + command);', miss: 'Process.Start("git", "status");' },
  },
  {
    id: "csharp-tls-verification-off",
    level: "signal",
    severity: "high",
    category: "security",
    files: csharpFiles,
    pattern: /ServerCertificate(?:Custom)?ValidationCallback\s*=\s*(?:\([^)]*\)|\w+)\s*=>\s*true|DangerousAcceptAnyServerCertificateValidator/,
    title: "TLS certificate checks turned off",
    failure: "The client accepts any certificate, so a network attacker can read and change the traffic.",
    examples: { hit: "handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;", miss: "handler.ClientCertificateOptions = ClientCertificateOption.Manual;" },
  },
  {
    id: "csharp-weak-hash",
    level: "signal",
    severity: "medium",
    category: "security",
    files: csharpFiles,
    pattern: /\b(?:MD5|SHA1)\.Create\s*\(|\bnew\s+(?:MD5|SHA1)CryptoServiceProvider\s*\(/,
    title: "Weak hash algorithm",
    failure: "MD5 and SHA-1 collisions are practical, so the hash cannot protect integrity or passwords.",
    examples: { hit: "using var hash = MD5.Create();", miss: "using var hash = SHA256.Create();" },
  },
  {
    id: "csharp-sql-concatenation",
    level: "signal",
    severity: "high",
    category: "security",
    files: csharpFiles,
    pattern: /\b(?:new\s+SqlCommand|FromSqlRaw|ExecuteSqlRaw)\s*\(\s*(?:\$"|"[^"]*"\s*\+)/,
    title: "SQL built with string interpolation",
    failure: "A value with a quote changes the query, which allows SQL injection.",
    examples: { hit: 'var command = new SqlCommand($"SELECT * FROM Users WHERE Id = {id}", connection);', miss: 'var command = new SqlCommand("SELECT * FROM Users WHERE Id = @id", connection);' },
  },
];
