import { type BuiltInRule, pythonFiles } from "./types";

const secretWords = "(?:token|secret|password|passwd|nonce|salt|session|otp|api_?key)";
const randomCall = "\\brandom\\.(?:random|randint|choice|choices|randrange|getrandbits)\\s*\\(";

export const pythonRules: readonly BuiltInRule[] = [
  {
    id: "py-eval",
    level: "signal",
    severity: "high",
    category: "security",
    files: pythonFiles,
    pattern: /(?<![\w.])(?:eval|exec)\s*\(/,
    title: "Code built from a string at runtime",
    failure: "If any part of the string comes from input, the input runs as Python code.",
    examples: { hit: "result = eval(expression)", miss: "model.eval()" },
  },
  {
    id: "py-unsafe-deserialization",
    level: "signal",
    severity: "high",
    category: "security",
    files: pythonFiles,
    pattern: /\b(?:pickle|cPickle|dill|marshal|shelve)\.(?:loads?|open)\s*\(|\byaml\.(?:unsafe_load|load)\s*\((?![^)]*Loader\s*=\s*(?:yaml\.)?C?SafeLoader)/,
    title: "Unsafe deserialization",
    failure: "Loading attacker-controlled bytes with this loader runs arbitrary code.",
    examples: { hit: "data = pickle.loads(payload)", miss: "data = json.loads(payload)" },
  },
  {
    id: "py-shell-command",
    level: "signal",
    severity: "high",
    category: "security",
    files: pythonFiles,
    pattern: /\bshell\s*=\s*True\b|\bos\.(?:system|popen)\s*\(/,
    title: "Command runs through a shell",
    failure: "A value with shell syntax such as `; rm -rf` runs as a second command.",
    examples: { hit: "subprocess.run(command, shell=True)", miss: 'subprocess.run(["git", "status"])' },
  },
  {
    id: "py-tls-verification-off",
    level: "signal",
    severity: "high",
    category: "security",
    files: pythonFiles,
    pattern: /\bverify\s*=\s*False\b|\b_create_unverified_context\s*\(/,
    title: "TLS certificate checks turned off",
    failure: "The client accepts any certificate, so a network attacker can read and change the traffic.",
    examples: { hit: "requests.get(url, verify=False)", miss: "requests.get(url, timeout=5)" },
  },
  {
    id: "py-weak-hash",
    level: "signal",
    severity: "medium",
    category: "security",
    files: pythonFiles,
    pattern: /\bhashlib\.(?:md5|sha1)\s*\((?![^)]*usedforsecurity\s*=\s*False)/,
    title: "Weak hash algorithm",
    failure: "MD5 and SHA-1 collisions are practical, so the hash cannot protect integrity or passwords.",
    examples: { hit: "digest = hashlib.md5(data).hexdigest()", miss: "digest = hashlib.md5(data, usedforsecurity=False).hexdigest()" },
  },
  {
    id: "py-insecure-random",
    level: "signal",
    severity: "low",
    category: "security",
    files: pythonFiles,
    pattern: new RegExp(`${secretWords}.*${randomCall}|${randomCall}.*${secretWords}`, "i"),
    title: "Predictable random value used for a secret",
    failure: "The random module is predictable, so an attacker can guess the value. Use secrets.",
    examples: { hit: "token = ''.join(random.choices(alphabet, k=32))", miss: "delay = random.random() * 3" },
  },
  {
    id: "py-sql-formatting",
    level: "signal",
    severity: "high",
    category: "security",
    files: pythonFiles,
    pattern: /\.(?:execute|executemany|raw)\s*\(\s*(?:f["']|["'][^"']*["']\s*(?:%|\+|\.format\s*\())/,
    title: "SQL built with string formatting",
    failure: "A value with a quote changes the query, which allows SQL injection.",
    examples: { hit: 'cursor.execute(f"SELECT * FROM users WHERE id = {user_id}")', miss: 'cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))' },
  },
  {
    id: "py-insecure-temporary-file",
    level: "signal",
    severity: "medium",
    category: "security",
    files: pythonFiles,
    pattern: /\btempfile\.mktemp\s*\(/,
    title: "Race-prone temporary file name",
    failure: "Another process can create the file between the name check and its use.",
    examples: { hit: "path = tempfile.mktemp()", miss: "handle = tempfile.NamedTemporaryFile()" },
  },
  {
    id: "py-debug-mode",
    level: "signal",
    severity: "medium",
    category: "security",
    files: pythonFiles,
    pattern: /^\s*DEBUG\s*=\s*True\b|\.run\s*\([^)]*\bdebug\s*=\s*True|\bautoescape\s*=\s*False\b/,
    title: "Debug mode or autoescape turned off",
    failure: "Debug pages expose code and settings, and turning off autoescape lets input run as script.",
    examples: { hit: "app.run(host=host, debug=True)", miss: "app.run(host=host)" },
  },
  {
    id: "py-breakpoint",
    level: "signal",
    severity: "medium",
    category: "correctness",
    files: pythonFiles,
    pattern: /^\s*(?:breakpoint\s*\(\s*\)|(?:import\s+i?pdb\s*;\s*)?i?pdb\.set_trace\s*\(\s*\))/,
    title: "Breakpoint left in",
    failure: "The process stops and waits for a debugger when it reaches this line.",
    examples: { hit: "    breakpoint()", miss: "    log_breakpoint(frame)" },
  },
  {
    id: "py-mutable-default",
    level: "signal",
    severity: "medium",
    category: "correctness",
    files: pythonFiles,
    pattern: /\bdef\s+\w+\s*\([^)]*=\s*(?:\[\]|\{\}|set\(\)|dict\(\)|list\(\))/,
    title: "Mutable default argument",
    failure: "The default object is shared across calls, so one call's changes leak into the next.",
    examples: { hit: "def add(item, items=[]):", miss: "def add(item, items=None):" },
  },
  {
    id: "py-bare-except",
    level: "signal",
    severity: "low",
    category: "correctness",
    files: pythonFiles,
    pattern: /^\s*except\s*:\s*(?:pass\s*)?(?:#.*)?$/,
    title: "Bare except",
    failure: "It also catches KeyboardInterrupt and SystemExit, and hides the real error.",
    examples: { hit: "    except:", miss: "    except ValueError:" },
  },
];
