import {
  type BuiltInRule,
  cFamilyFiles,
  configFiles,
  dockerFiles,
  manifestFiles,
  scriptFiles,
  sqlFiles,
  terraformFiles,
} from "./types";

export const universalRules: readonly BuiltInRule[] = [
  {
    id: "conflict-marker",
    level: "certain",
    severity: "high",
    category: "correctness",
    files: /./,
    pattern: /^(?:<{7}|>{7})(?: |$)/,
    title: "Unresolved merge conflict marker",
    failure: "The file keeps a conflict marker, so it no longer parses or ships both sides of the conflict.",
    examples: { hit: "<<<<<<< HEAD", miss: "<<<< not a marker" },
  },
  {
    id: "private-key",
    level: "certain",
    severity: "high",
    category: "security",
    files: /./,
    pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY-----/,
    title: "Private key committed",
    failure: "Anyone who can read the repository can use this key. Rotate it and load it from a secret store.",
    examples: { hit: "-----BEGIN OPENSSH PRIVATE KEY-----", miss: "-----BEGIN PUBLIC KEY-----" },
  },
  {
    id: "pipe-to-shell",
    level: "signal",
    severity: "medium",
    category: "security",
    files: scriptFiles,
    pattern: /\b(?:curl|wget)\b[^|\n]*\|\s*(?:sudo\s+)?(?:ba|z)?sh\b/,
    title: "Remote script piped into a shell",
    failure: "A changed or compromised remote script runs with this job's permissions, unpinned and unreviewed.",
    examples: { hit: "curl -fsSL https://example.com/install | bash", miss: "curl -fsSL https://example.com/install -o install.sh" },
  },
  {
    id: "world-writable",
    level: "signal",
    severity: "medium",
    category: "security",
    files: /./,
    pattern: /\bchmod\s+(?:-R\s+)?0?777\b|\bchmod(?:Sync)?\s*\([^)]*\b0o?777\b/,
    title: "World-writable permissions",
    failure: "Any local user or process can replace the file, which leads to code execution or tampering.",
    examples: { hit: "chmod -R 777 /app", miss: "chmod 755 /app" },
  },
  {
    id: "tls-verification-off-env",
    level: "signal",
    severity: "high",
    category: "security",
    files: configFiles,
    pattern: /\b(?:NODE_TLS_REJECT_UNAUTHORIZED|PYTHONHTTPSVERIFY)\s*[=:]\s*['"]?0\b|\bGIT_SSL_NO_VERIFY\s*[=:]\s*['"]?(?:1|true)\b/i,
    title: "TLS verification turned off for a process",
    failure: "Every TLS connection the process makes accepts any certificate, so a network attacker can read and change traffic.",
    examples: { hit: "NODE_TLS_REJECT_UNAUTHORIZED=0", miss: "NODE_TLS_REJECT_UNAUTHORIZED=1" },
  },
  {
    id: "destructive-migration",
    level: "signal",
    severity: "high",
    category: "correctness",
    files: sqlFiles,
    pattern: /\b(?:DROP\s+(?:TABLE|COLUMN|DATABASE|SCHEMA)|TRUNCATE\s+(?:TABLE\s+)?\w)/i,
    title: "Destructive schema or data change",
    failure: "The migration deletes data that a rollback cannot restore, and running code may still read it.",
    examples: { hit: "ALTER TABLE users DROP COLUMN email;", miss: "ALTER TABLE users ADD COLUMN email text;" },
  },
  {
    id: "empty-catch",
    level: "signal",
    severity: "low",
    category: "correctness",
    files: cFamilyFiles,
    pattern: /\bcatch\s*(?:\([^)]*\))?\s*\{\s*\}/,
    title: "Error swallowed by an empty catch",
    failure: "A failure inside the try block disappears, and the caller continues with a partial or wrong state.",
    examples: { hit: "} catch (error) {}", miss: "} catch (error) { log(error); }" },
  },
  {
    id: "docker-remote-add",
    level: "signal",
    severity: "low",
    category: "security",
    files: dockerFiles,
    pattern: /^\s*ADD\s+https?:\/\//i,
    title: "Dockerfile adds an unverified remote file",
    failure: "The image includes whatever the URL serves at build time, with no checksum.",
    examples: { hit: "ADD https://example.com/tool.tar.gz /opt/", miss: "ADD ./tool.tar.gz /opt/" },
  },
  {
    id: "privileged-container",
    level: "signal",
    severity: "high",
    category: "security",
    files: manifestFiles,
    pattern: /\bprivileged\s*:\s*true\b|\bhost(?:Network|PID|IPC)\s*:\s*true\b/,
    title: "Container runs privileged or shares host namespaces",
    failure: "A compromise of this container gives control of the host node.",
    examples: { hit: "  privileged: true", miss: "  privileged: false" },
  },
  {
    id: "public-cloud-resource",
    level: "signal",
    severity: "high",
    category: "security",
    files: terraformFiles,
    pattern: /\bpublicly_accessible\s*=\s*true\b|\bacl\s*=\s*"public-read(?:-write)?"|\bcidr_blocks\s*=\s*\[\s*"0\.0\.0\.0\/0"\s*\]/,
    title: "Cloud resource open to the internet",
    failure: "Anyone on the internet can reach the resource, which exposes its data or service.",
    examples: { hit: 'publicly_accessible = true', miss: 'publicly_accessible = false' },
  },
  {
    id: "wildcard-permission-policy",
    level: "signal",
    severity: "medium",
    category: "security",
    files: manifestFiles,
    pattern: /"Action"\s*:\s*"\*"|\bactions\s*=\s*\[\s*"\*"\s*\]/,
    title: "Permission policy allows every action",
    failure: "The principal can perform any action, so one leaked credential controls the whole account.",
    examples: { hit: '"Action": "*",', miss: '"Action": "s3:GetObject",' },
  },
  {
    id: "storage-encryption-off",
    level: "signal",
    severity: "medium",
    category: "security",
    files: terraformFiles,
    pattern: /\b(?:encrypted|storage_encrypted)\s*=\s*false\b/,
    title: "Storage encryption turned off",
    failure: "Data at rest is stored without encryption, so a leaked disk or snapshot exposes it.",
    examples: { hit: "storage_encrypted = false", miss: "storage_encrypted = true" },
  },
];
