import type { Workspace } from "./workspaces";

export const factsStart = "<!-- package-facts:start -->";
export const factsEnd = "<!-- package-facts:end -->";

function codeList(values: readonly string[]): string {
  return values.length === 0 ? "none" : values.map((value) => `\`${value}\``).join(", ");
}

export function renderFacts(workspace: Workspace): string {
  return [
    factsStart,
    "",
    "(generated by `bun run guides`; do not edit by hand)",
    "",
    `- Package name: \`${workspace.name}\``,
    `- Workspace dependencies: ${codeList(workspace.workspaceDependencies)}`,
    `- External dependencies: ${codeList(workspace.externalDependencies)}`,
    `- Export subpaths: ${codeList(workspace.exportSubpaths)}`,
    "",
    factsEnd,
  ].join("\n");
}

export type FactsBlock =
  | { readonly kind: "found"; readonly start: number; readonly end: number }
  | { readonly kind: "missing" };

export function findFactsBlock(text: string): FactsBlock {
  const start = text.indexOf(factsStart);
  const end = text.indexOf(factsEnd);

  if (start < 0 || end < start || text.indexOf(factsStart, start + 1) >= 0) {
    return { kind: "missing" };
  }

  return { kind: "found", start, end: end + factsEnd.length };
}

export function replaceFacts(options: {
  readonly text: string;
  readonly facts: string;
}): string | null {
  const block = findFactsBlock(options.text);

  return block.kind === "missing"
    ? null
    : `${options.text.slice(0, block.start)}${options.facts}${options.text.slice(block.end)}`;
}
